apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
  labels:
    info: nginx-with-rc
  annotations:
    description: trying nginx pod with replication controller
spec:
  replicas: 3
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 0 ##menunggu beberapa detik
            periodSeconds: 10 ##periode pengecekan
            timeoutSeconds: 1 ##limit timeout
            successThreshold: 1 ##pengeekan kesehatan (beberapa kali )
            failureThreshold: 3 ##perulanganpengecekan gaga;
