apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-annotations
  labels:
    version: 1.0.0
    environment: testing
  annotations:
    description: testing for annotations with 

spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"