apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    version: 1.0.0
    description: testing_kubernetes_without_labels
    environment: testing
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
